access_auth/urls.py
""" Auth Urls"""

# Django
from django.urls import path

# Local
from access_auth import views

urlpatterns = [

    path(
        route='',
        view= views.home,
        name='home'
    ),

    path(
        route='ingresar/',
        view=views.login_v,
        name='login'
    ),

    path(
        route='registrarse/',
        view=views.signup_v,
        name='signup'
    ),

    path(
        route='logout/',
        view=views.logout_v,
        name='logout'
    ),
    path(
        route='user/',
        view=views.getUserInfo,
        name='userInfo'
    ),

]

pages/urls.py
""" Pages Urls"""

# Django
from django.urls import path

# Local
from pages import views

urlpatterns = [

    path(
        route='',
        view= views.home,
        name='home'
    ),

    path(
        route='ingresar/',
        view=views.login_v,
        name='login'
    ),

    path(
        route='registrarse',
        view=views.signup_v,
        name='signup'
    )

]

trcobao/urls.py
# Django

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('auth/', include(('access_auth.urls', 'access_auth'), namespace='access_auth')),
    path('api/courses/', include(('courses.api_urls', 'api_courses'), namespace='api_courses')),
    path('api/activities/', include(('activities.api_urls', 'api_activities'), namespace='api_activities')),

    #Español
    path('api/grupos/', include(('courses.api_urls', 'api_courses'), namespace='api_grupos')),
    path('api/actividades/', include(('activities.api_urls', 'api_activities'), namespace='api_actividades')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block head_content %}{% endblock %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    
</head>
<body>

    {% include 'navbar.html' %}

    {% block content %}
    {% endblock%}
</body>
    {% block final %}
    {% endblock %}
</html>

templates/navbar.html
<nav class="navbar background-gray">
    <h1 class="navbar-title"> <a href="{% url 'access_auth:home' %}"><span>TR</span>COBAO</a></h1>
    <ul class="navbar-list">
        {% if user.is_authenticated %}
        <li><a href="#">{{user.first_name }}</a></li>
        <li><a href="{% url 'access_auth:logout' %}">Salir</a></li>
        {% else %}
        <li> <a href=""> Instrucciones</a></li>
        <li> <a href="{% url 'access_auth:login' %}"> Ingresar</a></li>
        <li> <a href="{% url 'access_auth:signup' %}"> Registrarse</a></li>
        {% endif %}
    </ul>
</nav>